#!/bin/bash

tmux new-session -d -s teleop

tmux split-window -h -t teleop:0
tmux split-window -h -t teleop:0.0
tmux split-window -h -t teleop:0.2

tmux select-layout -t teleop:0 even-horizontal

tmux split-window -v -t teleop:0.0
tmux split-window -v -t teleop:0.2
tmux split-window -v -t teleop:0.4
tmux split-window -v -t teleop:0.6

sleep 1

# 0 2 4 6
# 1 3 5 7

tmux send-keys -t teleop:0.0 'lg' C-m

tmux attach-session -t teleop
